= SPL2018.Project.06 - Hirakanaji-Task3

== Progress
* [x] 3 Präprozessoren
    ** [x] Copy source files from previous task
    ** [x] Implement features
        *** [x] Implement 2 features
        *** [x] Possibility to switch features on/off with preprocessors
    ** [x] Implement preprocessors (Antenna or Munge)
    ** [x] Test configurations and document errors in README
    ** [x] Modify feature model
        *** [x] Mark implemented features as "konkret"
        *** [x] Mark not implemented features as "abstrakt"

== Bugs
* Antenna: Wenn ein konkretes Feature ein Sub-Feature hat, das nicht angehakt ist (sodass bei dem konkreten Feature statt einem Haken ein gefülltes Quadrat angezeigt wird), dann wird es nicht als aktiviertes Feature in der Konfiguration durch Antenna erkannt (<feature automatic="selected" manual="selected" name="Scrambler"/>). Oder es hat etwas mit dem Constraint zu tun?

* Antenna versteht keine Leerzeichen in Feature-Namen - Workaround: Refactoring aller Features mit Leerzeichen